### ISSUE TITLE
[Test] scripts/test.sh may not put the libcls_arrow library to correct location

### ISSUE THREAD

**Issue by ljishen** [uccross/skyhookdm-arrow#222]
When following the [contribution guide](https://github.com/ljishen/skyhookdm-arrow/blob/arrow-master/cpp/src/arrow/adapters/arrow-rados-cls/docs/contributing.md), the CentOS environment in `uccross/skyhookdm-arrow:v0.2.0` has the default class lookup dir set to `@CMAKE_INSTALL_LIBDIR@/rados-classes`, which is `/usr/lib64/rados-classes`. This is not the path `/usr/lib/x86_64-linux-gnu/rados-classes/` the `test.sh` script supposes.

To make it portable, we can set the `osd class dir` for [osd] in the `ceph.conf`. This is the same way used by `vstart.sh` in Ceph.

**Comment by ljishen** [comment]
@JayjeetAtGithub Would you tell me what is the purpose of step 3 in the [contribution guide](https://github.com/uccross/skyhookdm-arrow/blob/arrow-master/cpp/src/arrow/adapters/arrow-rados-cls/docs/contributing.md)?

**Comment by JayjeetAtGithub** [comment]
@ljishen That looks like a very bad mistake. It should be step 2 or maybe we can omit it.

**Comment by ljishen** [comment]
@JayjeetAtGithub I see. Thanks for your response.

**Comment by JayjeetAtGithub** [comment]
@YashJipkate Can you please fix the above problem  ?

**Comment by YashJipkate** [comment]
I'll omit the point altogether then, just add a link to the docker page.
